export const weatherList = [
  "Blowing Or Drifting Snow",
  "Heavy Freezing Drizzle/Freezing Rain",
  "Light Freezing Drizzle/Freezing Rain",
  "Freezing Fog",
  "Heavy Freezing Rain",
  "Light Freezing Rain",
  "Funnel Cloud/Tornado",
  "Hail Showers",
  "Ice",
  "Lightning Without Thunder",
  "Mist",
  "Drizzle",
  "Precipitation In Vicinity",
  "Rain",
  "Heavy Rain And Snow",
  "Light Rain And Snow",
  "Rain Showers",
  "Heavy Rain",
  "Light Rain",
  "Sky Coverage Decreasing",
  "Sky Coverage Increasing",
  "Sky Unchanged",
  "Heavy Drizzle",
  "Smoke Or Haze",
  "Snow",
  "Snow And Rain Showers",
  "Snow Showers",
  "Heavy Snow",
  "Light Snow",
  "Squalls",
  "Thunderstorm",
  "Thunderstorm Without Precipitation",
  "Diamond Dust",
  "Light Drizzle",
  "Hail",
  "Overcast",
  "Partially cloudy",
  "Clear",
  "Heavy Drizzle/Rain",
  "Light Drizzle/Rain",
  "Dust storm",
  "Fog",
  "Freezing Drizzle/Freezing Rain",
];
